import { mkdir, writeFile } from 'node:fs/promises';
import { profile as p, cases, skills, timeline, education, languages, certifications, otherProjects } from '../src/content.ts';

const escape = (text: string) => text.replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]!));
const h = escape;
const arrow = '<span aria-hidden="true">↗</span>';
const cv = '/ahmad-nouh-public-cv.pdf';
const tags = (items: string[]) => `<ul class="tags" aria-label="Technologies">${items.map(item => `<li>${h(item)}</li>`).join('')}</ul>`;
const sun = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1.5 1.5m11 11L19 19M5 19l1.5-1.5m11-11L19 5"/></svg>';
const moon = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" aria-hidden="true"><path d="M20 14A8.5 8.5 0 0 1 10 3a8.5 8.5 0 1 0 10 11Z"/></svg>';
const orb = '<span class="twin-orb" aria-hidden="true"><i></i><i></i><i></i></span>';
const header = `<a class="skip" href="#main">Skip to content</a><header class="site-header wrap"><a class="wordmark" href="/" aria-label="Ahmad Nouh, home">Ahmad Nouh<span aria-hidden="true">.</span></a><nav aria-label="Main navigation"><a href="/#work">Work</a><a href="/#about">About</a><a href="#contact">Contact</a><a href="${cv}">CV ${arrow}</a></nav><button id="theme" class="theme-switch" type="button" role="switch" aria-checked="false" aria-label="Dark theme" title="Switch color theme"><span class="switch-thumb"></span>${sun}${moon}</button></header>`;
const contact = `<section class="contact wrap section" id="contact" aria-labelledby="contact-title"><div><p class="eyebrow">Let’s talk</p><h2 id="contact-title">Have something<br>in mind?</h2><p>I’m open to applied AI, LLM, NLP/search, and AI backend opportunities across EMEA.</p><a class="text-link email-link" href="mailto:${p.email}">${p.email} ${arrow}</a><div class="social-links"><a href="${p.linkedin}">LinkedIn ${arrow}</a><a href="${p.github}">GitHub ${arrow}</a></div></div><form id="lead-form"><div class="form-row"><label>Your name<input name="name" autocomplete="name" maxlength="100" required></label><label>Company<input name="company" autocomplete="organization" maxlength="140" required></label></div><label>Email<input name="email" type="email" autocomplete="email" maxlength="254" required></label><label>What would you like to discuss?<textarea name="message" rows="4" minlength="10" maxlength="3000" required placeholder="The role, project, or problem you have in mind…"></textarea></label><div class="honeypot" aria-hidden="true"><label>Website<input name="website" tabindex="-1" autocomplete="off"></label></div><p class="form-note">Submitting sends these details to Ahmad by email. <a href="/privacy/">Privacy details</a>.</p><div id="lead-challenge"></div><button class="button primary" type="submit">Send to Ahmad ${arrow}</button><p id="lead-status" class="form-status" role="status" aria-live="polite"></p></form></section>`;
const chat = `<dialog id="twin" aria-labelledby="twin-title"><div class="chat-layout"><aside class="chat-sidebar"><div class="twin-brand">${orb}<span>Another way<br>to meet Ahmad.</span></div><p class="eyebrow">Explore a thread</p><div class="suggestions"><button type="button" data-question="What did Ahmad build at Blink?"><span>01</span> Work at Blink ${arrow}</button><button type="button" data-question="Tell me about Ahmad’s Arabic NLP experience."><span>02</span> Arabic NLP ${arrow}</button><button type="button" data-question="How does Second Memory retrieve saved content?"><span>03</span> Second Memory ${arrow}</button><button type="button" data-question="What kind of engineering work does Ahmad do?"><span>04</span> Skills & approach ${arrow}</button></div><div class="chat-person"><img src="/ahmad-nouh.png" width="36" height="36" alt=""><div><strong>Ahmad Nouh</strong><span>AI Engineer · Istanbul</span></div></div><a href="#contact" id="chat-contact" class="text-link">Talk to the human ${arrow}</a></aside><div class="chat-main"><div class="chat-heading"><div><p class="eyebrow"><span class="status-dot"></span> Powered by public portfolio facts</p><h2 id="twin-title">Ahmad’s AI Twin <span class="ai-label">AI</span></h2></div><button class="icon-button" id="close-twin" aria-label="Close AI Twin">×</button></div><div id="chat-log" class="chat-log" role="log" aria-label="Conversation" aria-live="off"><div class="chat-welcome">${orb}<h3>A little curious?<br>You’re in the right place.</h3><p>I’m Ahmad’s AI assistant. Ask me about his work, the systems he’s built, or the thinking behind them.</p><div class="welcome-prompts"><button type="button" data-question="What did Ahmad build at Blink?">Work at Blink ↗</button><button type="button" data-question="Tell me about Ahmad’s Arabic NLP experience.">Arabic NLP ↗</button></div><span class="welcome-note">Start with a question. Follow your curiosity.</span></div></div><p id="chat-announcement" class="sr-only" role="status" aria-live="polite"></p><form id="chat-form"><label class="sr-only" for="chat-input">Your question</label><div class="chat-compose"><textarea id="chat-input" name="question" rows="2" maxlength="1200" required placeholder="What would you like to know?"></textarea><button id="send-chat" class="button primary" type="submit" aria-label="Send question">↑</button><button id="stop-chat" class="button secondary" type="button" aria-label="Stop response" hidden>■</button></div><div id="chat-challenge"></div><p id="chat-status" class="form-status" role="status"></p></form><p class="chat-disclosure">AI can make mistakes. Messages go to Groq to generate answers; this site does not store your chat.</p><div class="chat-footer"><button id="clear-chat" type="button" class="quiet-button">↺ New conversation</button><span>Enter to send · Shift + Enter for a new line</span><a href="/privacy/">Privacy</a></div></div></div></dialog>`;
const footer = `<footer class="wrap site-footer"><a class="wordmark" href="/">Ahmad Nouh<span>.</span></a><p>AI engineering. With purpose.</p><button class="quiet-button" id="motion-toggle" aria-pressed="false">Pause motion</button><button class="quiet-button" id="system-theme">Use device theme</button><a href="/privacy/">Privacy</a><span>© ${new Date().getFullYear()}</span></footer>${chat}`;

function page(title: string, description: string, path: string, body: string) {
  const url = `https://me.nouhlab.com${path}`;
  return `<!doctype html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="color-scheme" content="light dark"><meta name="theme-color" content="#dce2e1"><title>${h(title)}</title><meta name="description" content="${h(description)}"><link rel="canonical" href="${url}"><meta property="og:type" content="website"><meta property="og:title" content="${h(title)}"><meta property="og:description" content="${h(description)}"><meta property="og:url" content="${url}"><meta property="og:image" content="https://me.nouhlab.com/ahmad-nouh.png"><meta name="twitter:card" content="summary"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="preload" href="/fonts/bricolage-latin.woff2" as="font" type="font/woff2" crossorigin><script src="/theme.js"></script><script type="module" src="/src/main.ts"></script></head><body>${header}<main id="main">${body}${contact}</main>${footer}</body></html>`;
}

const motifs = [
  '<div class="match-art"><span class="orbit orbit-one"></span><span class="orbit orbit-two"></span><span class="match-center">b<span>link.</span></span><i class="match-node node-one"></i><i class="match-node node-two"></i><i class="match-node node-three"></i><span class="art-label">People. Sessions. Possibilities.</span></div>',
  '<div class="enrich-art"><span></span><span></span><span></span><span></span><span></span><strong>Connected<br>context.</strong></div>',
  '<div class="language-art"><span lang="ar">لغة</span><i>Arabic, understood.</i></div>',
];
const home = `<section class="hero wrap"><div class="hero-copy"><p class="eyebrow hero-enter"><span class="status-dot"></span> Ahmad Nouh <span class="small-divider">/</span> AI Engineer</p><h1><span class="hero-line"><span>Useful AI,</span></span><span class="hero-line"><span>built for the</span></span><span class="hero-line"><span class="gradient-text">real world.</span></span></h1><p class="hero-intro hero-enter">${h(p.intro)}</p><div class="hero-actions hero-enter"><a class="button primary" href="#work">Explore my work <span aria-hidden="true">↓</span></a><button class="button secondary" data-open-twin>${orb} Meet my AI Twin ${arrow}</button></div><p class="availability hero-enter"><span class="status-dot"></span>Istanbul, Turkey <span class="small-divider">/</span> Available across EMEA</p></div><aside class="hero-portrait"><div class="portrait-scene"><div class="portrait-ring ring-one"></div><div class="portrait-ring ring-two"></div><div class="portrait-frame"><img src="/ahmad-nouh.png" width="250" height="300" alt="Ahmad Nouh, smiling in a deep-teal hoodie" fetchpriority="high"></div><span class="floating-chip chip-one"><i aria-hidden="true">↗</i> AI applications</span><span class="floating-chip chip-two"><i aria-hidden="true">⌕</i> Search & retrieval</span><span class="floating-chip chip-three"><i aria-hidden="true" lang="ar">ع</i> Arabic NLP</span><span class="scene-cross" aria-hidden="true">✳</span></div><div class="portrait-caption"><span>Human curiosity.<br>Applied intelligence.</span><a href="${cv}" class="round-link" aria-label="View Ahmad’s public CV">${arrow}</a></div></aside><div class="hero-bottom"><span>Ideas are only the beginning.</span><a href="#work">Scroll to see what comes next <span aria-hidden="true">↓</span></a></div></section>
<section class="wrap section" id="work" aria-labelledby="work-title"><div class="section-heading" data-reveal><div><p class="eyebrow">01 / Selected work</p><h2 id="work-title">Real problems.<br><span class="muted">Thoughtful systems.</span></h2></div><p>Recommendations, enrichment, Arabic NLP.<br>A closer look at the work behind the words.</p></div><div class="work-grid">${cases.slice(0, 3).map((c, i) => `<a class="work-card work-${c.slug}" href="/work/${c.slug}/" data-reveal><div class="work-art" aria-hidden="true">${motifs[i]}<span class="art-index">0${i+1} / EXPERIENCE</span><span class="art-arrow">↗</span></div><div class="work-copy"><div class="card-meta"><span>${c.name}</span><span>${c.period}</span></div><h3>${h(c.title)}</h3><p>${h(c.summary)}</p>${tags(c.stack.slice(0, 3))}<span class="card-link">Inside the work ${arrow}</span></div></a>`).join('')}</div>
<article class="personal-project" data-reveal><div class="memory-art" aria-hidden="true"><div class="memory-halo"></div><div class="memory-note note-back"><span>WORTH KEEPING</span><i>Ideas don’t arrive<br>in one place.</i><div class="note-lines"></div></div><div class="memory-note note-front"><span>SECOND MEMORY</span><strong>Find the thought.<br>Keep the thread.</strong><div class="memory-search">⌕ &nbsp; That thing I saved…</div><div class="note-tags"><span>Article</span><span>Video</span><span>Repository</span></div></div><span class="memory-caption">Saved once. Found when it matters.</span></div><div class="memory-copy"><p class="eyebrow">04 / Independently built</p><h3>Second Memory<span class="accent">.</span></h3><p class="project-lede">A place for what you want to remember.</p><p>${h(cases[3].summary)}</p><div class="memory-flow" aria-label="Second Memory’s documented flow"><span>Save a URL</span><i aria-hidden="true">→</i><span>Add context</span><i aria-hidden="true">→</i><span>Find it again</span></div><a class="button secondary" href="/work/second-memory/">Explore the project ${arrow}</a></div></article><div class="other-projects">${otherProjects.map((project,i) => `<article data-reveal><span class="project-index">0${i+5}</span><div><p class="eyebrow">${h(project.stack)}</p><h3><a href="${project.url}">${project.name} ${arrow}</a></h3><p>${h(project.description)}</p></div></article>`).join('')}</div></section>
<section class="wrap section about" id="about" aria-labelledby="about-title"><div class="about-intro" data-reveal><p class="eyebrow">02 / A little about me</p><h2 id="about-title">Curious by nature.<br><span class="muted">Engineer by practice.</span></h2><div class="about-body"><p class="large-copy">${h(p.about)}</p><p>${h(p.style)}</p><p>Earlier, at Code Experts, I built Angular and Ionic interfaces for video-on-demand and taxi-booking products, contributed Node.js backend work, and built a WebSocket chat feature connecting drivers and riders.</p></div><a class="text-link" href="${cv}">The full story, in a CV ${arrow}</a></div><div class="timeline" data-reveal><div class="timeline-heading"><h3>The path so far</h3><span aria-hidden="true">↘</span></div>${timeline.map(([date, company, role],i) => `<div class="timeline-row"><span class="timeline-dot" aria-hidden="true"></span><span class="timeline-date">${date}</span><strong>${company}</strong><span class="timeline-role">${role}</span><span class="timeline-index" aria-hidden="true">0${i+1}</span></div>`).join('')}</div></section>
<section class="wrap section" id="skills" aria-labelledby="skills-title"><div class="section-heading" data-reveal><div><p class="eyebrow">03 / What I work with</p><h2 id="skills-title">From the model<br><span class="muted">to the moving parts.</span></h2></div><p>A toolkit built through research,<br>experimentation, and delivery.</p></div><div class="skill-list">${skills.map(([label, items], index) => `<details data-reveal${index === 0 ? ' open' : ''}><summary><span class="skill-number">0${index + 1}</span><h3>${h(label)}</h3><span class="expand-icon" aria-hidden="true">+</span></summary><div class="skill-content">${tags(items.split(', '))}</div></details>`).join('')}</div><div class="credentials"><div data-reveal><span class="credential-icon" aria-hidden="true">↗</span><h3>Education</h3><p><strong>Damascus University</strong><br>2015–2021</p><p>Bachelor’s degree in Information Technology Engineering<br><span class="muted">Artificial Intelligence specialization</span></p></div><div data-reveal><span class="credential-icon" aria-hidden="true">✳</span><h3>Selected certifications</h3><ul>${certifications.map(c => `<li>${h(c)}</li>`).join('')}</ul></div><div data-reveal><span class="credential-icon" aria-hidden="true">◎</span><h3>Languages</h3><ul>${languages.map(l => `<li>${h(l)}</li>`).join('')}</ul></div></div></section>
<section class="twin-invitation wrap" data-reveal><div class="twin-visual">${orb}<span class="orbit orbit-one"></span><span class="orbit orbit-two"></span></div><div><p class="eyebrow">04 / Follow your curiosity</p><h2>There’s more<br>to the story.</h2><p>Ask my AI Twin about my experience, projects, and approach.<br>A conversation, grounded in this portfolio.</p><button class="button primary" data-open-twin>Let’s start a conversation ${arrow}</button></div><span class="invitation-watermark" aria-hidden="true">Hello.</span></section>`;

await writeFile('index.html', page('Ahmad Nouh | AI Engineer, LLM Applications & Arabic NLP', p.intro, '/', home));
for (const [index, c] of cases.entries()) {
  const next = cases[(index + 1) % cases.length];
  const diagram = c.slug === 'second-memory' ? `<figure class="system-diagram"><figcaption><span class="eyebrow">Documented system</span><strong>From saved content to a grounded answer</strong></figcaption><ol><li><strong>Flutter</strong><span>Web + Android client<br>URL saving / share intents</span></li><li><strong>FastAPI</strong><span>Metadata & summaries<br>Tags, import / export</span></li><li><strong>PostgreSQL + pgvector</strong><span>Vector + full-text retrieval<br>Reciprocal Rank Fusion</span></li><li><strong>LangGraph</strong><span>Search & listing tools<br>Streaming answers + references</span></li></ol><p>Application deployed with Docker Compose. Hosted Groq inference and Gemini embeddings supply the model APIs.</p></figure>` : '';
  const body = `<article class="case wrap"><a class="back-link" href="/#work">← All work</a><header class="case-header"><p class="eyebrow">${c.number} / ${h(c.category)}</p><div class="case-identity"><p>${c.name}</p><span>${h(c.period)}<br>${h(c.role)}</span></div><h1>${h(c.title)}</h1><p class="case-intro">${h(c.intro)}</p>${tags(c.stack)}${'source' in c ? `<a class="text-link source-link" href="${c.source}">View source on GitHub ${arrow}</a>` : ''}</header><div class="case-content">${c.sections.map(s => `<section class="case-section"><p class="eyebrow">${h(s.label)}</p><div><h2>${h(s.title)}</h2>${s.paragraphs.map(text => `<p>${h(text)}</p>`).join('')}</div></section>`).join('')}${diagram}</div><div class="case-end"><button class="button secondary" data-open-twin data-context="Tell me more about Ahmad’s work on ${c.name}.">Ask the AI Twin about this ${arrow}</button><a class="next-case" href="/work/${next.slug}/"><span class="eyebrow">Next case study</span><strong>${next.name} ${arrow}</strong></a></div></article>`;
  await mkdir(`work/${c.slug}`, { recursive: true });
  await writeFile(`work/${c.slug}/index.html`, page(`${c.name} | Ahmad Nouh`, c.summary, `/work/${c.slug}/`, body));
}
await mkdir('privacy', { recursive: true });
await writeFile('privacy/index.html', page('Privacy | Ahmad Nouh', 'How this portfolio handles messages and AI conversations.', '/privacy/', `<article class="wrap privacy"><p class="eyebrow">Your information</p><h1>Privacy, in plain language.</h1><p>Last updated September 23, 2026.</p><h2>Browsing</h2><p>This portfolio does not use advertising or analytics cookies. Your theme choice is saved in your browser. Cloudflare hosts the site and processes connection information to deliver and protect it.</p><h2>Talking to the AI Twin</h2><p>The Twin is an AI assistant. When you send a question, your message and a short conversation history are sent to Groq with approved public portfolio facts. The site does not store chat transcripts on a server or email them to Ahmad. Messages remain in page memory until you clear them, navigate away, or reload. Groq processes the request under its own data policies. Avoid including sensitive information.</p><h2>Sending an inquiry</h2><p>Only submitting the contact form sends your name, email, company, and message to Ahmad through Resend. Your email is included as the reply-to address. The message remains in Ahmad’s mailbox so he can respond. To request deletion, email <a href="mailto:${p.email}">${p.email}</a>.</p><h2>Spam protection</h2><p>Cloudflare Turnstile checks submissions to reduce abuse. It may process browser and network signals. Both forms require a successful check before the services receive the submission.</p><h2>Service providers</h2><p><a href="https://www.cloudflare.com/privacypolicy/">Cloudflare privacy policy</a> · <a href="https://groq.com/privacy-policy/">Groq privacy policy</a> · <a href="https://resend.com/legal/privacy-policy">Resend privacy policy</a></p></article>`));
console.log('Rendered home, four case studies, and privacy page.');
