// Public subset of my_resume_knowledge_base.md, consolidated 2 October 2026.
// Keep the private source outside this repository. Pages and Twin share these facts.
export const profile = {
  name: 'Ahmad Nouh', role: 'AI Engineer', location: 'Istanbul, Turkey',
  headline: 'AI that earns its place.',
  intro: 'I build LLM applications, Arabic NLP, and retrieval systems, with the Python engineering that brings them into products.',
  availability: 'Open to opportunities across EMEA', email: 'ahmadnouh428@gmail.com',
  github: 'https://github.com/ahmadnouh97', linkedin: 'https://www.linkedin.com/in/ahmad-nouh/',
  about: 'My work connects applied AI with backend engineering: understanding model behavior, preparing data, designing APIs, and handling the latency and failures that appear in a real product. I have approximately six years of professional AI engineering experience through July 2026, preceded by web development.',
  style: 'I work best with clear outcomes, technical ownership, and time for focused execution. At Blink, that meant collaborating with product, frontend, mobile, QA, and backend colleagues to bring AI features through tests and staged releases.',
  focus: 'Applied AI, LLM applications, retrieval, Arabic NLP, and Python backend engineering.',
};
export const cases = [
  {
    slug: 'blink', name: 'Blink', period: 'Nov 2025 - Jul 2026',
    role: 'AI Engineer', location: 'Remote', headquarters: 'Falls Church, Virginia, US',
    category: 'Recommendations & agent workflows', title: 'AI inside an event platform.',
    summary: 'Delivered attendee matchmaking and session recommendations; designed a separate beta flight-creation agent and OCR-assisted document-extraction workflow.',
    stack: ['Python', 'FastAPI', 'PostgreSQL', 'pgvector', 'RabbitMQ', 'LangGraph', 'OCR', 'Docling', 'Gemini 2.5 Flash'],
    intro: 'Blink is an event-management platform with attendee, session, flight-creation, and hotel-reservation workflows. I worked on recommendation features and their supporting Python services, alongside agent evaluation and document understanding.',
    highlights: ['Delivered content-based attendee and session recommendations through tests, CI/CD, and staged releases.', 'Designed and evaluated a feature-flagged LangGraph flight-creation agent with five integrated tools.', 'Built OCR-assisted extraction of structured flight-ticket and hotel data from PDFs and images with Docling and Gemini 2.5 Flash.', 'Evaluated self-hosted Gemma 3 12B inference on AWS EC2 G5 GPUs.'],
    sections: [
      { title: 'Connecting attendees and sessions', label: 'Delivered recommendations', paragraphs: ['The problem was to match attendees and surface relevant sessions inside the event platform. I built content-based filtering capabilities using Python/FastAPI, PostgreSQL, and pgvector, and integrated the recommendation features into a distributed architecture using RabbitMQ.', 'The delivery included automated tests, CI/CD, and development, staging, and production releases. I collaborated across product and engineering teams. These recommendations were delivered independently of the beta agent. No recommendation uplift, ranking benchmark, or user-count result is recorded.'] },
      { title: 'Flight creation through a bounded workflow', label: 'Beta / feature-flagged', paragraphs: ['I designed and evaluated a LangGraph agent for flight creation within the event-management platform. Five integrated tools covered booking, attendee search, location lookup, and document parsing. The workflow connected AI outputs with backend services and remained behind a feature flag for beta evaluation.', 'A separate workflow combined optical character recognition (OCR) and multimodal document processing with Docling and Gemini 2.5 Flash to extract structured flight-ticket and hotel data from PDFs and images for platform workflows. This supports document extraction and tool integration experience; it does not establish autonomous ticket purchasing or a general-availability agent release.'] },
      { title: 'Measuring the feasibility of local inference', label: 'Research / evaluation', paragraphs: ['I evaluated Gemma 3 12B served through Ollama on AWS EC2 G5 GPUs. Measurements covered time to first token, token throughput, end-to-end latency, RAM/VRAM, and GPU utilization.', 'The purpose was to assess self-hosting feasibility. No numeric benchmark, cost saving, production traffic result, or final hosting decision is established by the available record.'] },
      { title: 'The engineering around the AI', label: 'Backend contribution', paragraphs: ['I built and maintained FastAPI services, asynchronous workflows, PostgreSQL-backed APIs, and external-service integrations. I contributed to backend refactoring intended to simplify services and improve multi-tenant support.', 'Claude Code was part of my engineering workflow for code, tests, documentation, and reports. Architecture work was a contribution alongside colleagues, without a claim of sole ownership or a measured refactoring gain.'] },
    ],
  },
  {
    slug: 'ment', name: 'MENT', period: 'Oct 2023 - Oct 2025',
    role: 'AI Engineer', location: 'Istanbul, Turkey / Hybrid', headquarters: 'Falls Church, Virginia, US',
    category: 'Enrichment & relationship intelligence', title: 'Better context. Less waiting.',
    summary: 'Parallel LLM extraction, clearer profile attribution, relationship graphs, and the services behind a privacy-first network-intelligence platform.',
    stack: ['Python', 'Azure OpenAI', 'Celery', 'Neo4j', 'n8n', 'MCP', 'RabbitMQ', 'Grafana'],
    intro: 'MENT is a privacy-first network-intelligence platform. My work covered collecting and enriching information, attributing it to the right profile, extracting structured fields, and exposing relationship insights through backend and conversational services.',
    highlights: ['Reduced a core AI pipeline from about 15 minutes to under 3 through parallel asynchronous extraction.', 'Improved data-to-profile attribution by approximately 33% versus the prior system.', 'Built a Neo4j relationship graph and contributed to n8n multi-agent enrichment with MCP tools.'],
    sections: [
      { title: 'Shortening the extraction pipeline', label: 'About 15 minutes to under 3', paragraphs: ['The core AI pipeline was taking about 15 minutes. I parallelized asynchronous LLM calls that extracted different schema sections, such as professional and personal fields, and handled mapping and validation in Python. The pipeline then ran in under 3 minutes, enabling interactions closer to real time.', 'This result belongs to asynchronous extraction and Python processing. It is separate from the Neo4j graph and multi-agent contributions. The workload size, percentile latency, and measurement protocol are not recorded.'] },
      { title: 'Attributing information to the right person', label: 'Approximately 33% improvement', paragraphs: ['Similar or identical names made data-to-profile attribution ambiguous. I improved attribution by approximately 33% versus the prior system, working on profile disambiguation and enrichment quality.', 'The exact metric definition, sample size, and relative-versus-absolute interpretation are not documented. This is an attribution result, not a 33-percentage-point accuracy gain or a knowledge-graph benchmark.'] },
      { title: 'Enrichment through cooperating workflows', label: 'Multi-agent contribution', paragraphs: ['I contributed to multi-agent enrichment in n8n, integrated Model Context Protocol tools, and contributed RabbitMQ integration and retries. Grafana tracing supported visibility into the workflows.', 'I also built and deployed Python microservices and Celery workers for background collection, enrichment, insight generation, and AI workloads. Azure OpenAI integrations supported retrieval and conversational services. Exact agent topology and agent counts are not established.'] },
      { title: 'Relationships that can be queried', label: 'Graph engineering', paragraphs: ['I designed and implemented a Neo4j graph of contact profiles and relationships. It supported insights around shared interests, employers, and multi-hop network connections.', 'This demonstrates graph data modeling and relationship traversal. The available evidence does not establish a production GraphRAG deployment or a causal link between the graph and the attribution measurement.'] },
    ],
  },
  {
    slug: 'lableb', name: 'Lableb', period: 'Aug 2020 - Sep 2023',
    role: 'AI Engineer', location: 'Damascus, Syria / Hybrid', headquarters: 'Dubai, UAE',
    category: 'Arabic NLP & service engineering', title: 'Arabic language, practical systems.',
    summary: 'A production spam-classification service alongside Arabic spelling correction, language-model research, and NLP microservices.',
    stack: ['Python', 'TensorFlow', 'Hugging Face', 'KenLM', 'DVC', 'Azure ML', 'Go / Fiber', 'Java / Spring Boot'],
    intro: 'At Lableb, I worked on Arabic NLP and search-related B2B systems, moving between model research, comparative experiments, data preparation, and service development. I first joined as an AI Engineer Intern in April-July 2020, then started the full-time role in August.',
    highlights: ['Built a production B2B spam-classification service handling up to 30,000 requests per day.', 'Filtered about 90% of spam queries, with attention to valid traffic and false positives.', 'Compared spelling-correction approaches and trained/evaluated Arabic NER, POS, and transliteration models.'],
    sections: [
      { title: 'Filtering spam in a production service', label: 'Up to 30,000 requests/day', paragraphs: ['I built a B2B spam-classification service handling up to 30,000 requests per day and detecting/filtering about 90% of spam queries. The work connected classification models with production service engineering, with attention to minimizing false positives on legitimate queries.', 'The 90% figure describes spam filtering. It is not established as overall accuracy, precision, or F1; no measured false-positive rate, customer count, or service-level objective is supplied.'] },
      { title: 'Comparing approaches to Arabic spelling', label: 'Research & engineering', paragraphs: ['I compared NLTK n-gram models and neural noisy-channel approaches through iterative spelling-correction experiments. Moving to KenLM improved runtime with comparable results. DVC versioned related datasets and model artifacts.', 'I researched, trained, and evaluated Arabic named entity recognition, part-of-speech tagging, transliteration, and spelling correction in Azure Machine Learning, using task-appropriate F1, precision, recall, and accuracy. These research activities are distinct from the production spam service.'] },
      { title: 'Serving language capabilities', label: 'NLP microservices', paragraphs: ['I built microservices for synonym extraction, spam filtering, English-to-Arabic transliteration, and converting unstructured text to structured data. Service work spanned Python/Flask, Go/Fiber, and Java/Spring Boot.', 'Data preparation and analysis used pandas, NumPy, Matplotlib, and Seaborn. I worked with other engineers on model and service delivery; the record does not assign every framework to a particular service or establish throughput for every NLP component.'] },
    ],
  },
  {
    slug: 'second-memory', name: 'Second Memory', period: 'Personal project',
    role: 'Design & engineering', location: 'Self-hosted application', headquarters: '',
    category: 'Personal knowledge & retrieval', title: 'A useful memory for the web.',
    summary: 'Save online discoveries, organize editable summaries and tags, and retrieve them through hybrid search and a tool-using assistant.',
    stack: ['Python', 'FastAPI', 'PostgreSQL', 'pgvector', 'LangGraph', 'Gemini embeddings', 'Groq', 'Flutter', 'Docker Compose'],
    source: 'https://github.com/ahmadnouh97/my-second-memory',
    intro: 'Second Memory is my personal application for saving articles, videos, posts, and repositories, then finding them again. It brings a FastAPI backend and PostgreSQL/pgvector retrieval together with a Flutter web and locally configured Android client.',
    highlights: ['Hybrid vector/full-text retrieval with Reciprocal Rank Fusion and account-scoped filters.', 'LangGraph search/listing tools, streamed responses, and server-validated saved-item references.', 'Editable titles, summaries, and reusable tags; JSON/CSV import/export with duplicate skipping.'],
    sections: [
      { title: 'Saving useful context, not just links', label: 'Product behavior', paragraphs: ['Saving a URL extracts public metadata/descriptions and produces editable titles, summaries, and tags. Tags can be reused, listed, renamed, or removed. The Flutter client supports web and locally configured Android share intents; saved items can be filtered by type and tags, with dates supported by the list API.', 'JSON and CSV import/export skip duplicates. Current ingestion works with metadata and summaries: it does not transcribe videos or index complete article bodies.'] },
      { title: 'Combining semantic and keyword retrieval', label: 'Hybrid search', paragraphs: ['The backend uses PostgreSQL 16 and pgvector. Gemini gemini-embedding-001 produces 768-dimensional embeddings with RETRIEVAL_DOCUMENT for saved titles/summaries and RETRIEVAL_QUERY for questions. Cosine-similarity candidates and PostgreSQL full-text results are fused with Reciprocal Rank Fusion, using constant 60.', 'Account ownership and tag/type filters are applied inside database queries before candidate limits. Specified embedding-provider failures fall back to keyword search; database errors still propagate. Search is over saved metadata/summaries, without a claim of passage-level document QA.'] },
      { title: 'References grounded in authorized results', label: 'Tool-using assistant', paragraphs: ['A LangGraph/LangChain assistant uses search and listing tools, with hosted Groq inference and the current documented default openai/gpt-oss-120b. SSE streams answers to Flutter. The server resolves saved-item cards from authorized tool results, discarding invented IDs and duplicate references.', 'Backend work includes Pydantic schemas/settings, SQLAlchemy asynchronous access, asyncpg, and Alembic migrations. The Flutter client uses Dart, Riverpod, go_router, and Freezed. Tests cover ranking, filters, ownership, provider fallback, streaming, and reference validation.'] },
      { title: 'Delivery and a small retrieval check', label: 'Personal deployment / evaluation', paragraphs: ['Docker Compose and migrations support self-hosting, with a documented VPS deployment path. GitHub Actions is documented for backend/Flutter tests, analysis, and the release web build. The application and database are self-hosted; Groq inference and Google embeddings remain external dependencies.', 'A recorded September 11, 2026 smoke run used eight manually labeled queries over eight synthetic notes: Recall@5 and MRR@5 were both 1.0, with median API latency 324.7 ms. This was one sequential pass with real Google embeddings after warmup/import, not a general accuracy, production-scale, or baseline-superiority result.'] },
    ],
  },
];
export const outcomes = [
  { value: '15 → <3 min', name: 'MENT / AI pipeline', detail: 'Parallel LLM extraction with Python mapping and validation. Approximate recorded runtime.' },
  { value: '≈6 years', name: 'Professional AI engineering', detail: 'Arabic NLP, LLM applications, retrieval, and Python services. Experience through July 2026.' },
  { value: '30,000/day', name: 'Lableb / spam service', detail: 'Up to 30,000 requests per day; about 90% of spam queries filtered.' },
];
export const skills = [
  { name: 'LLM applications & agents', context: 'Blink beta workflow, MENT enrichment, and Second Memory', description: 'Tool boundaries, structured outputs, OCR-assisted document extraction, model APIs, and asynchronous workflows that connect AI with product services.', tools: ['LangGraph', 'LangChain', 'MCP', 'n8n', 'Azure OpenAI', 'Groq', 'Gemini', 'OCR', 'Docling'] },
  { name: 'Retrieval & recommendations', context: 'Blink recommendations, MENT graph, and personal search projects', description: 'Content-based recommendations, vector and full-text search, RRF ranking, and graph relationship traversal.', tools: ['PostgreSQL', 'pgvector', 'Embeddings', 'Hybrid retrieval', 'RRF', 'Neo4j', 'ChromaDB', 'Sentence Transformers'] },
  { name: 'Backend & data', context: 'Python services across AI roles; earlier web and NLP services', description: 'Python is my primary language. I build APIs, workers, validation, messaging, and streaming around models and data.', tools: ['Python', 'SQL', 'FastAPI', 'Flask', 'Celery', 'RabbitMQ', 'SQLAlchemy', 'Pydantic', 'Alembic', 'SSE', 'Go / Fiber', 'Java / Spring Boot', 'Node.js'] },
  { name: 'Machine learning & Arabic NLP', context: 'Lableb research, Topic Classification, and SILA-4B', description: 'Spelling, NER, POS tagging, transliteration, classification, and comparative evaluation. QLoRA/PyTorch work is a personal experiment.', tools: ['TensorFlow', 'Keras', 'Hugging Face', 'KenLM', 'NLTK', 'PyTorch', 'QLoRA / PEFT', 'TRL', 'scikit-learn', 'pandas', 'NumPy', 'MLflow', 'DVC', 'Snorkel'] },
  { name: 'Cloud, delivery & evaluation', context: 'Azure model work, Blink GPU feasibility, and personal deployments', description: 'Automated checks, staged releases, tracing, and benchmarks chosen for the task: retrieval ranks, classification F1, or inference latency.', tools: ['Azure ML', 'AWS EC2 G5', 'Docker / Compose', 'GitHub Actions', 'Grafana', 'Ollama', 'Recall@k / MRR@k', 'BFCL / AST', 'TTFT / throughput', 'Cloudflare Pages'] },
  { name: 'Programming tools & workflow', context: 'Daily engineering and AI-assisted personal projects', description: 'I used Claude Code at Blink for code, tests, documentation, and reports, alongside Git and automated checks. My broader toolset includes Codex, Cursor, Jupyter, and Python development tools.', tools: ['Git', 'GitHub', 'GitLab', 'Claude Code', 'Codex', 'Cursor', 'uv', 'Jupyter', 'pytest', 'Ruff', 'Node test runner'] },
  { name: 'Interfaces & application development', context: 'Code Experts, Second Memory, and this portfolio', description: 'Angular/Ionic from earlier professional work; Flutter/Dart and TypeScript/Vite from personal applications. This portfolio uses native HTML/CSS.', tools: ['Angular', 'Ionic', 'JavaScript', 'TypeScript', 'Flutter', 'Dart', 'Riverpod', 'Streamlit', 'Vite', 'HTML / CSS'] },
];
export const timeline = [
  ['Nov 2025 - Jul 2026', 'Blink', 'AI Engineer / Remote'],
  ['Oct 2023 - Oct 2025', 'MENT', 'AI Engineer / Hybrid, Istanbul'],
  ['Aug 2020 - Sep 2023', 'Lableb', 'AI Engineer / Hybrid, Damascus'],
  ['Apr 2020 - Jul 2020', 'Lableb', 'AI Engineer Intern'],
  ['Oct 2018 - Jan 2020', 'Code Experts', 'Web Developer / On-site, Damascus'],
];
export const education = 'Bachelor’s degree in Information Technology Engineering, Artificial Intelligence specialization. Damascus University, 2015-2021.';
export const languages = ['Arabic - Native or bilingual proficiency', 'English - Professional working proficiency', 'Turkish - Elementary proficiency'];
export const certifications = ['DeepLearning.AI TensorFlow Developer / July 2021', 'Introduction to Machine Learning in Production / DeepLearning.AI', 'Natural Language Processing in TensorFlow / DeepLearning.AI / June 2021', 'Natural Language Processing with Probabilistic Models / DeepLearning.AI / March 2021', 'Python for Data Science and AI / IBM / September 2020'];
export const otherProjects = [
  { name: 'SILA-4B', status: 'Personal fine-tuning experiment', description: 'An Arabic tool-calling QLoRA experiment on Qwen3-4B using an 8 GB laptop GPU. Synthetic data, leakage checks, pinned inputs, and resumable paired evaluation made the result inspectable.', result: 'I built a workflow for synthetic-data preparation, QLoRA training, and controlled base-versus-adapter evaluation on an 8 GB GPU. With pinned inputs, leakage checks, and resumable benchmarks, I could inspect training outcomes and prepare a revised dataset for the next experiment.', stack: ['PyTorch', 'Transformers', 'PEFT', 'TRL', 'bitsandbytes', 'uv'], url: 'https://github.com/ahmadnouh97/sila-4b' },
  { name: 'Topic Classification', status: 'Personal ML / MLOps pipeline', description: 'An end-to-end topic-classification workflow connecting model training, hyperparameter tuning, prediction, and evaluation through MLflow, with a Streamlit interface for exploring data and running inference.', result: 'I connected training, hyperparameter tuning, prediction, and performance reporting in an MLflow pipeline, with experiment artifacts available for review. Through Streamlit and Snorkel slice analysis, users can explore the data, try predictions, and inspect model behavior across topic classes, emoji tweets, and short tweets.', stack: ['Python', 'scikit-learn', 'MLflow', 'Snorkel', 'Streamlit'], url: 'https://github.com/ahmadnouh97/e2e-topic-classification' },
  { name: 'IMDb Semantic Search', status: 'Personal retrieval demo', description: 'Find movies by meaning using all-MiniLM-L6-v2 sentence embeddings and ChromaDB, with a Streamlit interface over movie descriptions, titles, genres, dates, and crew metadata.', result: 'I built a movie-discovery demo that lets users search by meaning. The implementation connects IMDb data processing, sentence embeddings, and ChromaDB indexing with a Streamlit interface, covering the path from preparing movie metadata to querying a vector database and presenting results.', stack: ['Python', 'ChromaDB', 'Sentence Transformers', 'Streamlit'], url: 'https://github.com/ahmadnouh97/imdb-semantic-search' },
  { name: 'OnePass Face Recognition', status: 'Local computer-vision application', description: 'A local webcam/DroidCam application to detect, capture, and recognize previously seen faces. OpenCV-only fallback, optional MediaPipe detection, and DeepFace FaceNet512 embeddings support different environments.', result: 'I built a local application that connects camera input, face detection, capture, and recognition of previously seen faces. Users can configure the camera source and matching thresholds; I added local storage for face crops, embeddings, and capture metadata, plus an OpenCV-only fallback for environments without TensorFlow.', stack: ['Python', 'OpenCV', 'MediaPipe', 'DeepFace', 'uv'], url: 'https://github.com/ahmadnouh97/onepass-face-recognition' },
  { name: 'This portfolio & AI Twin', status: 'Personal web application', description: 'Generated static pages, a streamed Groq assistant grounded in shared public facts, and Cloudflare Pages Functions. Turnstile protects requests; explicit contact submissions use Resend.', result: 'I built a portfolio where visitors can explore case studies, ask contextual questions through a streamed AI assistant, and send an inquiry. Using AI-assisted development, I added keyboard navigation, theme and motion preferences, stop/retry controls, and API validation, with automated checks for streaming and provider failures.', stack: ['TypeScript', 'Vite', 'Cloudflare', 'Groq', 'SSE'], url: 'https://github.com/ahmadnouh97/ahmad-nouh-portfolio' },
];
export const codeExperts = {
  period: 'Oct 2018 - Jan 2020', role: 'Web Developer', location: 'Damascus, Syria / On-site',
  description: 'At Code Experts, I built Angular interfaces and contributed Node.js backend work for Vooliom, a video-on-demand product. For Alo Taxi, I built the Ionic mobile app and Angular 8 administration panel, and contributed to a WebSocket chat feature connecting drivers and riders.',
  stack: ['Angular', 'Ionic', 'Node.js', 'WebSockets'],
};
export const knowledgeNotes = {
  blinkExtraction: 'The documented work covers OCR-assisted extraction of structured flight-ticket and hotel data from PDFs and images using Docling and Gemini 2.5 Flash. The specific OCR backend, processing order, endpoint, storage, message bus, extracted field names, JSON schema, tests, release status, and measured savings for this extraction workflow are not documented. The delivered recommendation services and the separate beta LangGraph agent do not establish those details for OCR.',
  independentProjectLimits: 'IMDb Semantic Search is a personal demo without recorded retrieval-quality, latency, production-scale, or usage measurements. OnePass is a local personal application without an established recognition-accuracy or false-match benchmark; results depend on framing and lighting. Its implementation does not establish employer use or biometric-security suitability.',
  topicClassification: 'The contribution is an end-to-end MLflow pipeline: CLI training, hyperparameter tuning, prediction, experiment artifacts, and class/slice evaluation, alongside Streamlit data, performance, and inference views. Training from the UI, a deployed prediction service, model registry use, exact classifier architecture, and a verified held-out split are not established. A saved historic evaluation records weighted F1 0.815438 on 2,099 evaluation samples; this is not the training-set size, overall accuracy, or a baseline improvement. The run has not been retrained for this portfolio.',
  experience: 'Approximately six years of professional AI engineering through July 2026. Professional LLM work at MENT/Blink from October 2023 through July 2026, approximately three years rounded; not six years of LLM work. Official historic title AI Engineer; no formal people-management or staff-level tenure established.',
  boundaries: 'Employment dates and work locations are as listed. Headquarters are not residence. Internship projects and arrangement are not separately established. No production GraphRAG, Kubernetes cluster ownership, online A/B-testing result, or SAP experience established. Do not infer expert mastery of all project dependencies, or invent client names, testimonials, publications, awards, or metrics.',
  language: 'English is professional working proficiency, approximately B2 by self-report without certification. Turkish is elementary.',
  secondMemoryLimits: 'The record does not establish whether vector and full-text queries run concurrently, how account identity is transported in a request, or the hardware/hosting location of the smoke run. Fallback handles specified embedding-provider failures, not a claim that all provider errors are handled. Server validation constrains saved-item cards; it does not guarantee that natural-language answers cannot hallucinate. The small smoke run measures retrieval and latency, not correctness of the whole application or a security guarantee.',
  sila: 'SILA-4B is an AI-assisted personal fine-tuning experiment with controlled base-versus-adapter evaluation. Arabic exact tool calls: base model 58/70, trained adapter 53/70. English BFCL AST: base model 469/500, trained adapter 457/500. Arabic no-call decisions were unchanged at 17/30. The original adapter regressed and failed acceptance; fine-tuning did not improve these recorded results. Training used 6,600 synthetic examples, split into 5,280 training and 1,320 validation rows, with QLoRA NF4, LoRA rank 16, and selected epoch-one checkpoint 330. The separate evaluation contained 100 Arabic cases (70 call and 30 no-call) and 500 English cases. The revised follow-up corpus has 9,060 training and 2,328 validation rows. It was stopped at checkpoint 110 without a final evaluation; an early-stopping criterion is not established. Reported scores depend on local artifacts absent from the public repository; no general claim about Arabic or QLoRA follows from one run.',
};
export const publicFacts = JSON.stringify({ profile, cases, outcomes, skills, timeline, education, languages, certifications, otherProjects, codeExperts, knowledgeNotes });
